version: '3'

services:
  db-warehouse:
    image: "postgres:16"
    environment:
      - POSTGRES_PASSWORD=akhil199797
      - POSTGRES_USER=akhil97
      - POSTGRES_DB=mydatabase
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"

  etl-warehouse:

    build: .
      #command: "https://data.austintexas.gov/api/views/9t4d-g238/rows.csv"

    depends_on:
      - db-warehouse


volumes:
  db_data:
  

